apiVersion: v1
kind: Service
metadata:
  name: <APPNAME>
spec:
  ports:
  - name: tcp-<APPNAME>
    port: 8080
    protocol: TCP
    targetPort: tcp-<APPNAME>
  selector:
    app: <APPNAME>
  type: ClusterIP
